version: "3.6"

services:
  turradgiverapi:
    build:
      context: .
      dockerfile: turradgiver-api/Dockerfile.Net5
      target: dev
    container_name: turrad
    tty: true
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "./turradgiver-api/:/src/turradgiver-api"
      - "./turradgiver-bal/:/src/turradgiver-bal"
      - "./turradgiver-dal/:/src/turradgiver-dal"
      - "./turradgiver-test/:/src/turradgiver-test"
