version: "3.6"

services:
  turradgiverapi:
    build:
      context: .
      dockerfile: turradgiver-api/Dockerfile.Net5
      target: dev
    container_name: turrad
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - "./turradgiver-api/:/src/turradgiver-api"
      - "./data-access/:/src/data-access"
