on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
      - dev
  pull_request:
      types: [opened, synchronize, reopened]
name: Test
jobs: